#!/bin/bash

DIFF="$(git diff)"

git pull origin master
rc=$?; if [[ $rc != 0 ]]; then
  echo Git pull returned nonzero exit code && exit $rc
fi

if [[ "$DIFF" != "" ]]; then
  # There are differences
  echo "$DIFF"
  echo -n "There are differences between the local configs and the remote configs. Push changes? [y/N]"
  read answer
  if [[ "$answer" == "y" ]]; then
    git add . && git commit -m "Autoupdate config: $(date)"
    git push origin master
    if [[ "$?" != "0" ]]; then
      echo "Error pushing to master."
      exit $?
    fi
  fi
fi


DOTFILES_PATH="$(pwd)"

if [ -e ~/.bashrc ]; then
    PROFILE=~/.bashrc
elif [ -e ~/.bash_profile  ]; then
    PROFILE=~/.bash_profile
else
    PROFILE=/dev/null
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    cat ~/.bashrc           >> ~/.bashrc.bak
    cat ~/.config/i3/config >> ~/.config/i3/config.bak

    ln -svf 	$DOTFILES_PATH/sh 	        ~/.bashrc
    ln -svf 	$DOTFILES_PATH/sh 	        ~/.zshrc
    ln -svf 	$DOTFILES_PATH/i3		          ~/.config/i3/config
fi
if [[ "$OSTYPE" == "darwin"* ]]; then
    cat ~/.chunkwmrc        >> ~/.chunkwmrc.bak
    cat ~/.yabairc          >> ~/.yabairc.bak
    cat ~/.skhdrc           >> ~/.skhdrc.bak
    cat ~/.bash_profile     >> ~/.bash_profile.bak

    ln -svf 	$DOTFILES_PATH/sh	            ~/.bash_profile
    ln -svf 	$DOTFILES_PATH/sh	            ~/.zshrc
    ln -svf   $DOTFILES_PATH/chunkwm        ~/.chunkwmrc
    ln -svf   $DOTFILES_PATH/yabai          ~/.yabairc
    ln -svf   $DOTFILES_PATH/skhd           ~/.skhdrc
    ln -svf   $DOTFILES_PATH/xmodmap ~/.xmodmap
fi

# Backup
cat ~/.vimrc        >> ~/.vimrc.bak
cat ~/.inputrc      >> ~/.inputrc.bak
cat ~/.bash_profile >> ~/.bash_profile.bak
cat ~/.tmux.conf    >> ~/.tmux.conf.bak
cat ~/.config/kitty/kitty.conf >> ~/.config/kitty/kitty.conf.bak

ln -svf		$DOTFILES_PATH/vim		        ~/.vimrc
ln -svf		$DOTFILES_PATH/input		      ~/.inputrc
ln -svf   $DOTFILES_PATH/tmux           ~/.tmux.conf
ln -svf   $DOTFILES_PATH/kitty           ~/.config/kitty/kitty.conf
ln -svf   $DOTFILES_PATH/emacs          ~/.emacs.d
ln -svf	  $DOTFILES_PATH/nvim		 ~/.config/nvim/init.vim
